### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JunioCalu** [jo1gi/audiobook-dl#10]
On Manjaro Linux 21.2.1
 
 $ audiobook-dl -c ../cookies-audiobooks-com.txt https://www.audiobooks.com/book/stream/492141    
Finding compatible source
Downloading metadata
Downloading 0 files - Bíblia Sagrada King James Atualizada - Antig…  …
Traceback (most recent call last):
  File "/usr/bin/audiobook-dl", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.3.0', 'console_scripts', 'audiobook-dl')())
  File "/usr/lib/python3.10/site-packages/audiobook_dl-0.3.0-py3.10.egg/audiobookdl/__main__.py", line 52, in run
  File "/usr/lib/python3.10/site-packages/audiobook_dl-0.3.0-py3.10.egg/audiobookdl/download.py", line 31, in download
IndexError: list index out of range

**Comment by jo1gi** [comment]
I think I have fixed the problem.

**Comment by JunioCalu** [comment]
> I think I have fixed the problem.

Thanks so much for the quick support! But the program was only able to download the first chapter of the audio book, that is, 1 hour of audio, this book is a bible, and it is 80 hours long in total. There are multiple files.

Below I leave my session cookie for you to check
[cookies-www-audiobooks-com.txt](https://github.com/jo1gi/audiobook-dl/files/7877699/cookies-www-audiobooks-com.txt)

audiobook-dl -c cookies-audiobooks-com.txt https://www.audiobooks.com/book/stream/492141

**Comment by jo1gi** [comment]
Didn't know it was possible to audiobooks with have multiple files. I only have some with single files. I will see what I can do about the problem.

**Comment by jo1gi** [comment]
Sorry I took so long. I'm having problems reproducing your problem. All books i have checked only consists of one file, even books that are 72 hours long. I think you are missing some cookies in the cookie file. Did you export all cookies from `audiobooks.com` and not just `www.audiobooks.com`?

**Comment by jo1gi** [comment]
> would you have an up-to-date cookie capture extension recommendation?

I use https://github.com/rotemdan/ExportCookies on Firefox.

**Comment by JunioCalu** [comment]
> > would you have an up-to-date cookie capture extension recommendation?
> 
> I use https://github.com/rotemdan/ExportCookies on Firefox.

I used the same
