### ISSUE TITLE
Audiobooks.com > No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by CeliaMerino** [jo1gi/audiobook-dl#102]
**Installation method:**
github repo

**Version:**
Python 3.12.3
audiobook-dl 0.7.3

**Describe the bug**
hi! i've been trying to use the app but i get the error "No module named 'urllib3.packages.six.moves'" when i download from audiobooks.com. I also tried storytel and that worked fine
I tried to uninstall and reinstall urllib3, six & requests packages and also tried to downgrade the python version but none of that worked

**Command output**
Traceback (most recent call last):
  File "/opt/homebrew/bin/audiobook-dl", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.7.3', 'console_scripts', 'audiobook-dl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/audiobook-dl", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/homebrew/lib/python3.12/site-packages/audiobook_dl-0.7.3-py3.12.egg/audiobookdl/__init__.py", line 2, in <module>
  File "/opt/homebrew/lib/python3.12/site-packages/audiobook_dl-0.7.3-py3.12.egg/audiobookdl/utils/audiobook.py", line 2, in <module>
  File "/opt/homebrew/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/opt/homebrew/lib/python3.12/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/opt/homebrew/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/opt/homebrew/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

**Comment by Popkin2020** [comment]
![download audiobooks com](https://github.com/jo1gi/audiobook-dl/assets/64218014/83eb9a2f-3466-4b9e-a3a7-6925aa93614a)
Just download from audiobooks like this, very ez

**Comment by jo1gi** [comment]
Looks like it is a problem with python 3.12
