### ISSUE TITLE
add cloudlibrary support

### ISSUE THREAD

**Issue by evafans** [jo1gi/audiobook-dl#12]
It is similar to overdrive, audiobook on cloudlibrary is streaming on the website and no DRM.

**Comment by jo1gi** [comment]
I have been working on it, but I would like to get another login for testing.

**Comment by evafans** [comment]
https://www.guelphpl.ca/en/index.aspx
https://ebook.yourcloudlibrary.com/library/guelphpl/Browse
You may register a digital card using false information for testing, It won't cause any harm, the account will be automatically deleted after some time.

**Comment by Spectroxx** [comment]
Your last implementation seems to work good for me.

**Comment by jo1gi** [comment]
Yourcloudlibrary support should work now.

**Comment by evafans** [comment]
C:\audiobook-dl-master>audiobook-dl -c ‪C:\audiobook-dl-master\cookies-ebook-yourcloudlibrary-com.txt https://ebook.yourcloudlibrary.com/library/guelphpl/AudioPlayer/6np95r9
Finding compatible source
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\audiobook-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.3.0', 'console_scripts', 'audiobook-dl')())
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.3.0-py3.9.egg\audiobookdl\__main__.py", line 37, in run
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.3.0-py3.9.egg\audiobookdl\utils\source.py", line 41, in load_cookie_file
  File "C:\Program Files\Python39\lib\http\cookiejar.py", line 1798, in load
    with open(filename) as f:
OSError: [Errno 22] Invalid argument: '?C:\\audiobook-dl-master\\cookies-ebook-yourcloudlibrary-com.txt'

**Comment by evafans** [comment]
C:\audiobook-dl-master>audiobook-dl -c C:\audiobook-dl-master\cookies-yourcloudlibrary-com.txt https://ebook.yourcloudlibrary.com/library/guelphpl/AudioPlayer/6np95r9
Finding compatible source
Downloading metadata
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\audiobook-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.3.0', 'console_scripts', 'audiobook-dl')())
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.3.0-py3.9.egg\audiobookdl\__main__.py", line 43, in run
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.3.0-py3.9.egg\audiobookdl\download.py", line 17, in download
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.3.0-py3.9.egg\audiobookdl\sources\yourcloudlibrary.py", line 28, in before
TypeError: 'NoneType' object is not iterable

C:\audiobook-dl-master>

**Comment by evafans** [comment]
I encounter these two errors.

**Comment by jo1gi** [comment]
Are you sure you downloaded the newest version? I just pushed some changes and those errors don't match the new code.

**Comment by Spectroxx** [comment]
I just tested the newest version on Ubuntu 20.04.4. I had no Issues.

**Comment by jo1gi** [comment]
Try to download audiobook-dl again. Maybe something went wrong. The errors doesn't seem right.

**Comment by jo1gi** [comment]
@jaegercoder I think there are too many cookies in the cookie file. Try only exporting cookies from yourcloudlibrary.

**Comment by jo1gi** [comment]
@jaegercoder I think I fixed to problem. Try again with cookies from ebook.yourcloudlibrary.com.

**Comment by jaegercoder** [comment]
@jo1gi Thanks for working on this but now I get "List index out of range error. The data displayed in debug mode is quite huge hence not pasting it here. Let me know if you want the output with debug on.

```
audiobook-dl -c cookies-ebook-yourcloudlibrary-com.txt https://ebook.yourcloudlibrary.com/library/nypl/AudioPlayer/9e66kr9 >> debug.txt
Finding compatible source
Downloading metadata
Traceback (most recent call last):
  File "/usr/local/bin/audiobook-dl", line 11, in <module>
    load_entry_point('audiobook-dl==0.3.0', 'console_scripts', 'audiobook-dl')()
  File "/usr/local/lib/python3.8/dist-packages/audiobook_dl-0.3.0-py3.8.egg/audiobookdl/__main__.py", line 53, in run
  File "/usr/local/lib/python3.8/dist-packages/audiobook_dl-0.3.0-py3.8.egg/audiobookdl/download.py", line 23, in download
  File "/usr/local/lib/python3.8/dist-packages/audiobook_dl-0.3.0-py3.8.egg/audiobookdl/utils/source.py", line 125, in metadata
  File "/usr/local/lib/python3.8/dist-packages/audiobook_dl-0.3.0-py3.8.egg/audiobookdl/sources/yourcloudlibrary.py", line 38, in get_metadata
IndexError: list index out of range
```

**Comment by jaegercoder** [comment]
> @jaegercoder Made some new changes. Let's try again.

Works perfectly now. Thanks

**Comment by evafans** [comment]
I tried the latest version, now my problem is also solved.
