### ISSUE TITLE
Everand: No connection adapters were found

### ISSUE THREAD

**Issue by Popkin2020** [jo1gi/audiobook-dl#125]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Scripts\audiobook-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 31, in main
    process_url(url, options, config)
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 54, in process_url
    result = source.download(url)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\everand.py", line 24, in download
    return self.download_book_from_url(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\everand.py", line 78, in download_book_from_url
    files = self.get_files(book_info),
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\everand.py", line 105, in get_files
    return self.get_internal_files(book_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\everand.py", line 119, in get_internal_files
    return self.get_stream_files(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\source\networking.py", line 62, in get_stream_files
    key = self._get_page(seg.key.absolute_uri, headers=headers),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\source\__init__.py", line 103, in _get_page
    resp = self.get(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\source\networking.py", line 29, in get
    resp = self._session.get(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wheej\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'skd://drmtoday?keyId=9af3582a-1aa0-ef2f-adc6-919bdf19ff8a'

**Comment by scorpionking674** [comment]
I'm getting the same exact issue as well

**Comment by joshmans** [comment]
I have this issue on my mac as well

**Comment by slothphase** [comment]
same here

**Comment by NoxBlox** [comment]
Same issue for me and two others attempting installation separately. All on PC and all trying this after an initial install. Version 0.7.3 Have tried uninstalling and reinstalling via pip and then git. All same results. Also tried different options for cookies file. In install directory as cookies.txt, pointed at with copy path and as location listed in created config file. All same results. I'm assuming this is user install error somewhere. Just can't figure out where.

**Comment by devnoname120** [comment]
Epubor Everand Converter still works, even though it goes through the Android app of Everand, has a terrible UI, is costly, and is super slow: https://www.epubor.com/everand-downloader-user-guide.html

The free trial enables you to decrypt 1 audiobook.

**Comment by jo1gi** [comment]
Everand has changed how their encryption works. The new system will have to be implemented for Everand to work.

**Comment by devnoname120** [comment]
@jo1gi It seems to use Widevine L3 on the browser. I'm not sure if there is a way around it. On my side using the usual https://github.com/devine-dl/pywidevine to decrypt the stream works fine.

**Comment by devnoname120** [comment]
@jo1gi See here to manually download and decrypt the audiobooks with the new protection: https://github.com/jo1gi/audiobook-dl/issues/129#issuecomment-2395413515

It shouldn't be too complicated to integrate the solution in `audiobook-dl`. Users will need to provide their own `.wvd` CDM though.
