### ISSUE TITLE
Storytel Cloudflare block

### ISSUE THREAD

**Issue by xzakier** [jo1gi/audiobook-dl#137]
Installation method:
Github repo & pip/pypi (tried 2 times)

Version: 0.7.3
Python version : 3.12

Describe the bug
Finding compatible source
Authenticating with storytel
ERROR: Access blocked by Cloudflare

**Comment by fedeD84** [comment]
Same issue for me.

**Comment by xdaGari** [comment]
Changing the device ID in audiobookdl/sources/storytel.py (Line 173) fixed it for me.

**Comment by fedeD84** [comment]
@xdaGari  exacty how you changed it?

**Comment by ssakkout** [comment]
@fedeD84
 i have created a pull request to update the device id #138

**Comment by freddy36** [comment]
Thank you, included in the latest release:
https://github.com/jo1gi/audiobook-dl/releases/tag/v0.76

**Comment by msebastian100** [comment]
@freddy36  not fixed 

Finding compatible source
Authenticating with storytel
ERROR: Access blocked by Cloudflare

**Comment by munchbp** [comment]
> Thank you, included in the latest release: https://github.com/jo1gi/audiobook-dl/releases/tag/v0.76

git command gets v0.7.3 and also I tried downloading the latest zip and it still is v0.7.3

**Comment by fedeD84** [comment]
blocked again, same error

**Comment by freddy36** [comment]
should be fixed by https://github.com/jo1gi/audiobook-dl/pull/140
https://github.com/jo1gi/audiobook-dl/releases/tag/v0.7.7

**Comment by fedeD84** [comment]
it seems fixed now, thanks

**Comment by notavailable-1** [comment]
Blocked again :(

**Comment by fedeD84** [comment]
i can confirm that blocked again

**Comment by dev-O-T** [comment]
If you update user agent with these, it will be fine:

Storytel/24.52
Release/2288809

**Comment by fedeD84** [comment]
I have changed user agent but get same error

**Comment by dev-O-T** [comment]
Works for me. Just tried again. I don't have other changes. 

Without the user agent change I get cloudflare blocked error.

**Comment by fedeD84** [comment]
You changed it in storytel.py right it’s only one string

**Comment by notavailable-1** [comment]
> Works for me. Just tried again. I don't have other changes.
> 
> Without the user agent change I get cloudflare blocked error.

Wich version of audiobook-dl do you use? 
In wich file do you make these changes?
where in this file do you make these changes?

thanks for your help :)

**Comment by dev-O-T** [comment]
The latest with random uuid.

Installed with:
pip install --user
"git+https://github.com/jo1gi/audiobook-dl.git"

I looked the version numbers from Play Store's latest Storytel release.

storytel.py line 167:
"User-Agent": "Storytel/24.52 (Android 14; Google Pixel 8 Pro) Release/2288809",

**Comment by notavailable-1** [comment]
> The latest with random uuid.
> 
> Installed with: pip install --user "git+https://github.com/jo1gi/audiobook-dl.git"
> 
> I looked the version numbers from Play Store's latest Storytel release.
> 
> storytel.py line 167: "User-Agent": "Storytel/24.52 (Android 14; Google Pixel 8 Pro) Release/2288809",

and you have the audiobook in your shelf and copy the link from your browser?

**Comment by dev-O-T** [comment]
No. I never put them to shelf. I only copy the links from the browser and it works.

**Comment by notavailable-1** [comment]
k. i dont get. same version here + edit in storytel.py and it gives me blocked by cloudflare

**Comment by fedeD84** [comment]
same to me

**Comment by dev-O-T** [comment]
I did fresh install on laptop (with python 3.11). With user agent change it started working.

Previous trials were on my phone with python 3.8.

I wonder how have you installed your audiobook-dl. If you cloned with git, did you run the "python3 setup.py install" after changes?

With pip installation "setup.py install" not needed.

**Comment by notavailable-1** [comment]
> I did fresh install on laptop (with python 3.11). With user agent change it started working.
> 
> Previous trials were on my phone with python 3.8.
> 
> I wonder how have you installed your audiobook-dl. If you cloned with git, did you run the "python3 setup.py install" after changes?
> 
> With pip installation "setup.py install" not needed.

im on Python 3.12.8. install via pip installation

**Comment by fedeD84** [comment]
I’ve tryed a fresh install in venv but same result

**Comment by dev-O-T** [comment]
Perhaps your IP is blocked due to previous attempts? Can you try to change the IP or use different connection? VPN?

**Comment by fedeD84** [comment]
No, not related to IP block, tryed with VPN and have same error. Sure you don't have specific configuration? For example how you donwlod abook without put it in shelf? For me never worked without

**Comment by dev-O-T** [comment]
I use following bash script (script name: storytel-dl) as wrapper, and I give link as parameter:

#!/bin/bash
audiobook-dl --username foo@bar.com --password baz --library Storytel -d $1

Usage example:
bash storytel-dl https://www.storytel.com/fi/books/men-are-from-mars-women-are-from-venus-824493

**Comment by dev-O-T** [comment]
Now I'm experiencing strange issue that on one device the access is blocked by cloudflare, and with other device the accesses are not blocked.

The random uuid and my local user agent changes are used on both of them.

Both are in the same local network with the same public IP.

**Comment by freddy36** [comment]
@dev-O-T can you compare openssl versions (including pyhton version and python openssl module)?
They used TLS fingerprinting in the past to block python requests.

**Comment by dev-O-T** [comment]
The working one is with:
Python 3.8.18
OpenSSL 1.1.1v

Blocked:
Python 3.11.2
OpenSSL 3.0.15

**Comment by fedeD84** [comment]
@dev-O-T in my situation i've installed OpenSSL 3.3.2 and Python 3.12.6. Until 2/3 days ago no issue with download

**Comment by dev-O-T** [comment]
The one I had working is blocked now too.

**Comment by JerukPurut404** [comment]
Still not working

**Comment by dev-O-T** [comment]
Got it working locally by migrating from requests to curl_cffi.requests. Very minimal changes required.

**Comment by notavailable-1** [comment]
> Got it working locally by migrating from requests to curl_cffi.requests. Very minimal changes required.

good to hear :) where do you make these changes or how?

**Comment by fedeD84** [comment]
> Got it working locally by migrating from requests to curl_cffi.requests. Very minimal changes required.

Good, can you tell us where you make changes? Thanks

**Comment by dev-O-T** [comment]
Sure,

audiobookdl/sources/source/__init__.py:
#import requests
import curl_cffi

And in the end of file:
    def create_session(self, options: Any) -> curl_cffi.requests.Session:
        session = curl_cffi.requests.Session()
#        ssl_context: SSLContext = self.create_ssl_context(options)
        # session.adapters.pop("https://", None)
#        session.mount("https://", CustomSSLContextHTTPAdapter(ssl_context))
        return session


audiobookdl/sources/storytel.py:1
from curl_cffi.requests.models import Response

audiobookdl/utils/audiobook.py:3:
from curl_cffi import requests


I think thats all. 

I get one warning while running, but the downloaded file is ok:
download.py:187: UserWarning: chunk_size is ignored, there is no way to tell curl that.
  for chunk in request.iter_content(chunk_size=1024):

**Comment by notavailable-1** [comment]
> Sure,
> 
> audiobookdl/sources/source/**init**.py:
> 
> ```
> #import requests
> import curl_cffi
> ```
> 
> And in the end of file:
> 
> ```
>     def create_session(self, options: Any) -> curl_cffi.requests.Session:
>         session = curl_cffi.requests.Session()
> #        ssl_context: SSLContext = self.create_ssl_context(options)
>         # session.adapters.pop("https://", None)
> #        session.mount("https://", CustomSSLContextHTTPAdapter(ssl_context))
>         return session
> ```
> 
> audiobookdl/sources/storytel.py:1 `from curl_cffi.requests.models import Response`
> 
> audiobookdl/utils/audiobook.py:3: `from curl_cffi import requests`
> 
> I think thats all.
> 
> I get one warning while running, but the downloaded file is ok: download.py:187: UserWarning: chunk_size is ignored, there is no way to tell curl that. for chunk in request.iter_content(chunk_size=1024):
> 
> I don't know will this break other sources. It was just quick and dirty trial, and luckily the first download with Storytel worked.

With these changes i get blocked by cloudflare. like before. wich version of python and openssl do you have with your working config. and do use use these Storytel/24.52
Release/2288809 or the standard config that comes with 0.7.7?
thank you :)

**Comment by fedeD84** [comment]
> Sure,
> 
> audiobookdl/sources/source/**init**.py:
> 
> ```
> #import requests
> import curl_cffi
> ```
> 
> And in the end of file:
> 
> ```
>     def create_session(self, options: Any) -> curl_cffi.requests.Session:
>         session = curl_cffi.requests.Session()
> #        ssl_context: SSLContext = self.create_ssl_context(options)
>         # session.adapters.pop("https://", None)
> #        session.mount("https://", CustomSSLContextHTTPAdapter(ssl_context))
>         return session
> ```
> 
> audiobookdl/sources/storytel.py:1 `from curl_cffi.requests.models import Response`
> 
> audiobookdl/utils/audiobook.py:3: `from curl_cffi import requests`
> 
> I think thats all.
> 
> I get one warning while running, but the downloaded file is ok: download.py:187: UserWarning: chunk_size is ignored, there is no way to tell curl that. for chunk in request.iter_content(chunk_size=1024):
> 
> I don't know will this break other sources. It was just quick and dirty trial, and luckily the first download with Storytel worked.

I've made changes but i get this errore while trying download:
"/audiobookdl/utils/audiobook.py", line 3, in <module>
    from curl_cffi import requests

**Comment by notavailable-1** [comment]
do you have  curl_cffi installed? pip install curl_cffi

**Comment by fedeD84** [comment]
> pip install curl_cffi

I'm stupid... sorry now it works

**Comment by dev-O-T** [comment]
I did a Python script for sniffing the TLS fingerprints, and got some values while opening the latest official Android client.

Just in case someone wants to try with the same fingerprints:


**IPv6:**
JA3 Fingerprint: 771,4865,4866,4867,49195,49196,52393,49199,49200,52392,49171,49172,156,157,47,53,, Hash: 59fad7e58fa57d3f0545624f6814de3a

**IPv4:**
JA3 Fingerprint: 771,4865,4866,4867,49195,49196,52393,49199,49200,52392,**49161**,**49162**,49171,49172,156,157,47,53,, Hash: aef0bb248d17ef28d4dee53e4f0485c7


IPv4 is slightly different.

**Comment by rickyspanish8** [comment]
not working for me.  :(

**Comment by fedeD84** [comment]
> not working for me. :(

have you change all files?

**Comment by rickyspanish8** [comment]
Yes I did. Do I need to reinstall after that? with sudo python3 setup.py install?

**Comment by notavailable-1** [comment]
> Yes I did. Do I need to reinstall after that? with sudo python3 setup.py install?

nope.
do you have curl_cffi installed? pip install curl_cffi

wich version did you use?
wich changes have you applied?

**Comment by rickyspanish8** [comment]
im using the last version, pulled from github.

my utils/audiobook.py file https://pastebin.com/k5C1g1s9
my sources/source _init_.py  https://pastebin.com/qzw05BfT
and my sources/storytel.py  https://pastebin.com/KGgXiyL4

I did install curl_cffi and Im using the command audiobook-dl -c <here I put the name of the cookies file that its in the same directory of audiobook-dl>  <and here I paste the url from storytel>  
I have no idea what can I be doing wrong.

**Comment by notavailable-1** [comment]
> im using the last version, pulled from github.
> 
> my utils/audiobook.py file https://pastebin.com/k5C1g1s9 my sources/source _init_.py https://pastebin.com/qzw05BfT and my sources/storytel.py https://pastebin.com/KGgXiyL4
> 
> I did install curl_cffi and Im using the command `audiobook-dl -c <here I put the name of the cookies file that its in the same directory of audiobook-dl> <and here I paste the url from storytel> ` I have no idea what can I be doing wrong.

did you get any error message?

**Comment by notavailable-1** [comment]
> All releases of `audiobook-dl` since version `0.7.3` still say version `0.7.3`, which is very annoying when you have issues allegedly resolved in more recent versions.
> 
> In anyhoot, I tried to follow your suggestion [@dev-O-T](https://github.com/dev-O-T), but to no avail.
> 
> `%AppData%\..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\source\__init__.py`
> 
> > 8:#import requests
> > 9:import curl_cffi
> 
> [...]
> 
> > 196:    def create_session(self, options: Any) -> curl_cffi.requests.Session:
> > 197:        session = curl_cffi.requests.Session()
> > 198:#        ssl_context: SSLContext = self.create_ssl_context(options)
> > 199:        # session.adapters.pop("https://", None)
> > 200:#        session.mount("https://", CustomSSLContextHTTPAdapter(ssl_context))
> > 201:        return session
> 
> `%AppData%\..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\storytel.py`
> 
> > 1:#from requests.models import Response
> > 2:from curl_cffi.requests.models import Response
> 
> `%AppData%\..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\utils\audiobook.py`
> 
> > 2:#import requests
> > 3:from curl_cffi import requests
> 
> Installed the new requirement: `pip install curl_cffi`
> 
> But I get the same error message:
> 
> > DEBUG audiobook-dl 0.7.3
> > DEBUG python 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
> > INFO Finding compatible source
> > INFO Authenticating with storytel
> > DEBUG Logging in
> > ERROR: Access blocked by Cloudflare
> 
> **Traceback**:
> 
> > Traceback (most recent call last):
> > File "%AppData%..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl__main__.py", line 33, in main process_url(url, options, config)
> > File "%AppData%..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl__main__.py", line 53, in process_url authenticate(url, source, options, config)
> > File "%AppData%..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl__main__.py", line 143, in authenticate login(url, source, options, source_config)
> > File "%AppData%..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl__main__.py", line 123, in login source.login(url, **login_data)
> > File "%AppData%..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\source__init__.py", line 96, in login self._login(url, **kwargs)
> > File "%AppData%..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\storytel.py", line 171, in _login self._do_login()
> > File "%AppData%..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\storytel.py", line 190, in _do_login self.check_cloudflare_blocked(resp)
> > File "%AppData%..\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\storytel.py", line 160, in check_cloudflare_blocked raise CloudflareBlocked audiobookdl.exceptions.CloudflareBlocked
> 
> Thank you for trying to help.
> 
> Edit: I am on Windows, and I need to run audiobook from python with the `-m` flag to run the module as a script, or it won't work.
> 
> Full CLI command: `python -m audiobookdl -d -- username <email> --password <password> <audiobook url>`

dou you have installed the lasted version of audiobook? if you cant check this - just delete the actual modul and install the latest version with 0.7.7.

maybe add the tip from dev>

storytel.py line 167:
"User-Agent": "Storytel/24.52 (Android 14; Google Pixel 8 Pro) Release/2288809",

**Comment by dev-O-T** [comment]
> I did install curl_cffi and Im using the command `audiobook-dl -c <here I put the name of the cookies file that its in the same directory of audiobook-dl> <and here I paste the url from storytel> ` I have no idea what can I be doing wrong.

Have you tried to use username and password instead of cookies?

**Comment by dev-O-T** [comment]
I did my own [fork](https://github.com/dev-O-T/audiobook-dl), if someone want to skip the manual edits. 

Perhaps the source changes can be cherry picked to this original repo too.

**Comment by rickyspanish8** [comment]
> > I did install curl_cffi and Im using the command `audiobook-dl -c <here I put the name of the cookies file that its in the same directory of audiobook-dl> <and here I paste the url from storytel> ` I have no idea what can I be doing wrong.
> 
> Have you tried to use username and password instead of cookies?

just tried. didn't work.

**Comment by dev-O-T** [comment]
> maybe add the tip from dev>
> 
> storytel.py line 167: "User-Agent": "Storytel/24.52 (Android 14; Google Pixel 8 Pro) Release/2288809",

I did some trials, and figured out, it's the release number that matters. Not the version number in User-Agent string.

At the moment there is rule: Release > 2288629

Release/2288630 is the first working number. 

I can put arbitrary number as version. Even Storytel/00.01 works.

**Comment by mrrepel** [comment]
> I did my own [fork](https://github.com/dev-O-T/audiobook-dl), if someone want to skip the manual edits.
> 
> Perhaps the source changes can be cherry picked to this original repo too.

Sir, you have won the internet for today, it works like a charm!

**Comment by dev-O-T** [comment]
Nice @Suspect-byte !

Well.. this **audio**book-dl was intended for audiobooks, I guess. I didn't want to ruin it by adding the ebook support to my published fork lol. I have it locally tho. I found parts of that code somewhere, but I don't remember where I found em nor who did those edits originally. 

I'll push at some point.

**Comment by Suspect-byte** [comment]
@dev-O-T you got discord or something? I made it working with ebooks and removed the some errors. Well claude removed them for me I dont know any code ;)

**Comment by nonab** [comment]
@Suspect-byte can you create a fork and put code there?

**Comment by Suspect-byte** [comment]
@nonab sure thats amazing. Im not really good with github just chatgpt and claude are my teachers ;)
