### ISSUE TITLE
ModuleNotFoundError: No module named 'audiobookdl.__main__.run'; 'audiobookdl.__main__' is not a package

### ISSUE THREAD

**Issue by catfordfire** [jo1gi/audiobook-dl#21]
Any advice resolving that error? MacOS, have cloned and compiled, and have the cookies.txt file, but this is what I get.

thanks in advance!

**Comment by catfordfire** [comment]
here is the full error:
Traceback (most recent call last):
  File "/opt/homebrew/bin/audiobook-dl", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.4.1', 'console_scripts', 'audiobook-dl')())
  File "/opt/homebrew/bin/audiobook-dl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1001, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'audiobookdl.__main__.run'; 'audiobookdl.__main__' is not a package

**Comment by jo1gi** [comment]
Sorry, that's my fault. It looks like I messed up when changing the build system. I have uploaded a fix now.

**Comment by catfordfire** [comment]
confirmed working! many thanks for the lightning fast response :)
