### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'

### ISSUE THREAD

**Issue by hcbille** [jo1gi/audiobook-dl#25]
I get an error when I run the package on Linux. 
This is a fresh install on Debian.

hcbille@penguin:~/Audiobook-WebGUI$ audiobook-dl
Traceback (most recent call last):
  File "/home/hcbille/.local/bin/audiobook-dl", line 5, in <module>
    from audiobookdl.__main__ import run
  File "/home/hcbille/.local/lib/python3.9/site-packages/audiobookdl/__init__.py", line 2, in <module>
    from .sources.source import Source
  File "/home/hcbille/.local/lib/python3.9/site-packages/audiobookdl/sources/__init__.py", line 1, in <module>
    from .source import Source
  File "/home/hcbille/.local/lib/python3.9/site-packages/audiobookdl/sources/source/__init__.py", line 2, in <module>
    from . import networking
  File "/home/hcbille/.local/lib/python3.9/site-packages/audiobookdl/sources/source/networking.py", line 1, in <module>
    from audiobookdl import AudiobookFile, exceptions, logging
  File "/home/hcbille/.local/lib/python3.9/site-packages/audiobookdl/exceptions.py", line 2, in <module>
    from .logging import print_error_file, error
  File "/home/hcbille/.local/lib/python3.9/site-packages/audiobookdl/logging.py", line 48, in <module>
    def progress(progress_format: list[str | ProgressColumn]) -> Progress:
TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'

**Comment by jo1gi** [comment]
@hcbille audiobook-dl used a feature that was first available in python 3.10. I have changed it now. Hope it works.
