### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by hcbille** [jo1gi/audiobook-dl#26]
Trying to download this book from nextory: [https://www.nextory.se/bok/allt-vi-inte-ser-s%C3%A5-p%C3%A5verkas-du-av-det-osynliga-arbetet-hemma-och-p%C3%A5-jobbet-11866672/](https://catalog-se.nextory.com/bok/allt-vi-inte-ser-s%C3%A5-p%C3%A5verkas-du-av-det-osynliga-arbetet-hemma-och-p%C3%A5-jobbet-11866672/)

`audiobook-dl --username XXXXX --password YYYYY https://www.nextory.se/bok/allt-vi-inte-ser-s%C3%A5-p%C3%A5verkas-du-av-det-osynliga-arbetet-hemma-och-p%C3%A5-jobbet-11866672/ -o /audiobook/{title}`

I'm guessing it's `-o /audiobook/{title}` that break everything due to the ":" in the book-title. 

I have a few more examples of booktitles that fail the same way, most likely due to the "illegal" characters:

- [https://www.nextory.se/bok/1-metoden-sm%C3%A5-f%C3%B6r%C3%A4ndringar-stora-resultat-ett-enkelt-och-bepr%C3%B6vat-s%C3%A4tt-att-skapa-goda-vanor-och-bryta-d%C3%A5liga-10906761/](https://catalog-se.nextory.com/bok/1-metoden-sm%C3%A5-f%C3%B6r%C3%A4ndringar-stora-resultat-ett-enkelt-och-bepr%C3%B6vat-s%C3%A4tt-att-skapa-goda-vanor-och-bryta-d%C3%A5liga-10906761/)

```
exit status 1

Finding compatible source
Downloading metadata
Traceback (most recent call last):
  File "/usr/local/bin/audiobook-dl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 44, in run
    run_on_url(options, url)
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 65, in run_on_url
    download(s, options)
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/output/download.py", line 32, in download
    filenames = download_files_output(source, files, output_dir)
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/output/download.py", line 66, in download_files_output
    setup_download_dir(output_dir)
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/output/download.py", line 58, in setup_download_dir
    os.makedirs(path)
  File "/usr/lib64/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/audiobook/Allt vi inte ser : så påverkas du av det osynliga arbetet - hemma och på jobbet'
```

**Comment by hcbille** [comment]
Sorry I keep coming with bug-reports 😓

**Comment by jo1gi** [comment]
Are you still on Debian? I don't think it should be a problem with ":" characters on linux.

**Comment by hcbille** [comment]
This is in a redhat docker container. 

This specifically: https://github.com/hcbille/my-olivetin

**Comment by jo1gi** [comment]
I have created a new option `--remove-chars` that should remove characters you specify from the final path. It is also uploaded to pypi.

**Comment by hcbille** [comment]
`audiobook-dl --username XXXXXXXX --password YYYYYYYY https://www.nextory.se/bok/1-metoden-sm%C3%A5-f%C3%B6r%C3%A4ndringar-stora-resultat-ett-enkelt-och-bepr%C3%B6vat-s%C3%A4tt-att-skapa-goda-vanor-och-bryta-d%C3%A5liga-10906761/ --output-format ":%" -o /audiobook/{title}`

```
Finding compatible source
Downloading metadata
Traceback (most recent call last):
  File "/usr/local/bin/audiobook-dl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 56, in run
    run_on_url(options, url)
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 77, in run_on_url
    download(s, options)
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/output/download.py", line 28, in download
    output_dir = output.gen_output_location(
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/output/output.py", line 54, in gen_output_location
    for c in remove_chars:
TypeError: 'NoneType' object is not iterable
```

I updated it with pip and got this error instead 😓 I've tried wrapping it in "", '' and not wrapping it at all.

**Comment by jo1gi** [comment]
`--output-format` is for specifying file formats like mp3 or m4b. Use `--remove-chars` to remove chars.

**Comment by hcbille** [comment]
🙈 Sorry

**Comment by jo1gi** [comment]
It's ok. I found out I had another bug.

**Comment by hcbille** [comment]
Works now! Ty for a quick turnaround!
