### ISSUE TITLE
--combine tag results in error

### ISSUE THREAD

**Issue by catfordfire** [jo1gi/audiobook-dl#28]
Sorry... one more from me. If I add the --combine tag, I get the following error: 

Converting files
Combining files
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/__main__.py", line 56, in run
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/__main__.py", line 77, in run_on_url
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/download.py", line 47, in download
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/download.py", line 149, in combined_audiobook
audiobookdl.exceptions.FailedCombining

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/audiobook-dl", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.4.3', 'console_scripts', 'audiobook-dl')())
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/__main__.py", line 58, in run
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/exceptions.py", line 12, in print
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/logging.py", line 35, in print_error_file
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/logging.py", line 24, in read_asset_file
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 2362, in read_text
    with self.open('r', *args, **kwargs) as strm:
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 2342, in open
    raise FileNotFoundError(self)
FileNotFoundError: /opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/assets/errors/failed_combining.txt

**Comment by jo1gi** [comment]
Hope it works now
