### ISSUE TITLE
--combine works for mp3, but if --output-format m4b is used in addition, only the first chapter is saved

### ISSUE THREAD

**Issue by catfordfire** [jo1gi/audiobook-dl#29]
sorrrrrrry.....

No script errors occur, but the resulting m4b file is only (I think) the first chapter of the book. The conversion from mp3 to m4b works fine for the individual chapters, but the --combine flag seems to confuse something. to clarify - this all works perfectly now without the --output-format flag.

**Comment by jo1gi** [comment]
It's because the library I use for adding chapters does not support m4b files. It should work with mp3 files, also if you use `--combine`.

**Comment by catfordfire** [comment]
hi - thanks. makes sense.

**Comment by jo1gi** [comment]
I have made a temporary fix. It just requires ffmpeg. Please tell me if you have any problems.

**Comment by catfordfire** [comment]
Hi - it didn't work for me, unfortunately. It converted all to m4b and then combined to a file of only the first chapter.

**Comment by jo1gi** [comment]
I tried again. Hope it works now.

**Comment by catfordfire** [comment]
sadly not :( this is what I see. Could it be something on my end?

Converting files
Combining files
Adding chapters
Traceback (most recent call last):
  File "/opt/homebrew/bin/audiobook-dl", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.4.3', 'console_scripts', 'audiobook-dl')())
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/__main__.py", line 56, in run
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/__main__.py", line 77, in run_on_url
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/download.py", line 47, in download
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/download.py", line 152, in combined_audiobook
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/download.py", line 160, in embed_metadata_in_file
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/metadata/__init__.py", line 31, in add_chapters
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/metadata/ffmpeg.py", line 35, in add_chapters_ffmpeg
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/metadata/ffmpeg.py", line 22, in create_tmp_chapter_file
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/output/metadata/ffmpeg.py", line 10, in create_chapter_text
  File "/opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/utils/__init__.py", line 23, in read_asset_file
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 2362, in read_text
    with self.open('r', *args, **kwargs) as strm:
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 2342, in open
    raise FileNotFoundError(self)
FileNotFoundError: /opt/homebrew/lib/python3.10/site-packages/audiobook_dl-0.4.3-py3.10.egg/audiobookdl/assets/ffmpeg_chapter_template.txt

**Comment by jo1gi** [comment]
> Could it be something on my end?

I think it is. It looks like there is a file it can't find. Maybe try uninstalling and installing it again? You could also try running it directly with `python -m audiobookdl [options] <url>`.

**Comment by catfordfire** [comment]
thanks. I'll look into it. I tried the direct command, but different error. I think I'll stick to auto-m4b for now, as that's working well on a docker. Thanks so much for trying to resolve this for me! Hope it helps other people :)
