### ISSUE TITLE
AttributeError: module 'functools' has no attribute 'cache'

### ISSUE THREAD

**Issue by TheSupraLife** [jo1gi/audiobook-dl#33]
When I run:
_`audiobook-dl --username <username> --password <password> <url of storytel audiobook>`_

I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/audiobook-dl", line 5, in <module>
    from audiobookdl.__main__ import run
  File "/usr/local/lib/python3.8/dist-packages/audiobookdl/__init__.py", line 1, in <module>
    from .utils.audiobook import AudiobookFile, Chapter
  File "/usr/local/lib/python3.8/dist-packages/audiobookdl/utils/__init__.py", line 4, in <module>
    @functools.cache
AttributeError: module 'functools' has no attribute 'cache'
```

What am I doing wrong?

**Comment by jo1gi** [comment]
Nothing. I was using a function that was first introduced in python 3.9. I have removed it now on the Github version.

**Comment by jo1gi** [comment]
@TheSupraLife Did it work?

**Comment by TheSupraLife** [comment]
@jo1gi Can you provide me a example of a query to get it to work with storytel?

My input:
`audiobook-dl --username <username> --password <password> <url of storytel audiobook>`

Thanks in advance!

**Comment by jo1gi** [comment]
That should work if the url looks like ` https://www.storytel.com/<lang>/books/<book-id>` and the book is in your bookshelf. If it doesn't please send me the command output with the `--debug` argument.
