### ISSUE TITLE
Saxo: Nonseries book

### ISSUE THREAD

**Issue by PeaceMonster** [jo1gi/audiobook-dl#34]
**Installation method:**
Github repo

**Version:**
Python version 3.10.10 and audiobook-dl version latest

**Describe the bug**
Når man downloader en non-series book kaster den en fejl. 
Har lavet en midlertidig løsning lokalt ved at ud kommenterer `result.series = metadata["seriesName"]`

**Command output**
python -m audiobookdl --username *username*  --password *password* --combine https://www.saxo.com/dk/good-omens_lydbog-download_9780061967078

Traceback (most recent call last):
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ugilt3/audiobook-dl/audiobookdl/__main__.py", line 102, in <module>
    run()
  File "/home/ugilt3/audiobook-dl/audiobookdl/__main__.py", line 61, in run
    run_on_url(options, url)
  File "/home/ugilt3/audiobook-dl/audiobookdl/__main__.py", line 83, in run_on_url
    download(s, options)
  File "/home/ugilt3/audiobook-dl/audiobookdl/output/download.py", line 22, in download
    audiobook = create_audiobook(source)
  File "/home/ugilt3/audiobook-dl/audiobookdl/output/download.py", line 41, in create_audiobook
    metadata = source.get_metadata(),
  File "/home/ugilt3/audiobook-dl/audiobookdl/sources/saxo.py", line 95, in get_metadata
    result.series = metadata["seriesName"]
KeyError: 'seriesName'

**Comment by jo1gi** [comment]
Så er det fixet
