### ISSUE TITLE
getting user not authorized over all accounts

### ISSUE THREAD

**Issue by catfordfire** [jo1gi/audiobook-dl#36]
Hi again - I'm not sure if this is a bug or something being throttled on my accounts, but I've tried over three accounts (checked the cookies file for each) and tried multiple audiobooks, and am getting the same error each time. Are you able to replicate this? If not, please feel to trash this and I'll see what's happening on my accounts. Latest release installed.

DEBUG audiobook-dl 0.4.4
DEBUG python 3.10.9 (main, Dec 15 2022, 10:44:50) [Clang 14.0.0 
(clang-1400.0.29.202)]
DEBUG Searching for missing dependencies
Finding compatible source
DEBUG Could not find match from https://www.scribd.com/listen/xxxxxxxxxxx with 
(?<=(external_id":"))(scribd_)?\d+
ERROR: User not authorized

Make sure you have given the correct cookies with the --cookie
argument or with --username and --password, and
have all the right permissions to access the book you are trying to download.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/audiobookdl/sources/scribd.py", line 88, in prepare
    book_id = self.find_in_page(
  File "/opt/homebrew/lib/python3.10/site-packages/audiobookdl/sources/source/__init__.py", line 138, in find_in_page
    raise DataNotPresent
audiobookdl.exceptions.DataNotPresent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/audiobookdl/__main__.py", line 61, in run
    run_on_url(options, url)
  File "/opt/homebrew/lib/python3.10/site-packages/audiobookdl/__main__.py", line 83, in run_on_url
    download(s, options)
  File "/opt/homebrew/lib/python3.10/site-packages/audiobookdl/output/download.py", line 22, in download
    audiobook = create_audiobook(source)
  File "/opt/homebrew/lib/python3.10/site-packages/audiobookdl/output/download.py", line 35, in create_audiobook
    source.prepare()
  File "/opt/homebrew/lib/python3.10/site-packages/audiobookdl/sources/scribd.py", line 93, in prepare
    raise UserNotAuthorized
audiobookdl.exceptions.UserNotAuthorized

**Comment by jo1gi** [comment]
Which book?

**Comment by catfordfire** [comment]
This was the last one I tried, but I'm getting it for all
https://www.scribd.com/audiobook/543307954/Mindset-Shifts-Embracing-a-Life-of-Personal-Growth

**Comment by jo1gi** [comment]
I get the same error. I will try to find a fix.

**Comment by catfordfire** [comment]
thanks! much appreciated

**Comment by jo1gi** [comment]
Think it works now

**Comment by catfordfire** [comment]
Confirmed working again! Thanks so much as ever :)

**Comment by pranavmalikk** [comment]
i'm getting this same error, what was the fix?

I'm getting:
Finding compatible source
Authenticating with scribd
ERROR: User not authorized

Make sure you have given the correct cookies with the --cookie
argument or with --username and --password, and
have all the right permissions to access the book you are trying to download.
Traceback (most recent call last):
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/scribd.py", line 75, in download_book_from_url
    book_id = self.download_book_id(url)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/scribd.py", line 157, in download_book_id
    return self.find_in_page(
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/source/__init__.py", line 147, in find_in_page
    raise DataNotPresent
audiobookdl.exceptions.DataNotPresent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/__main__.py", line 32, in main
    process_url(url, options, config)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/__main__.py", line 53, in process_url
    result = source.download(url)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/scribd.py", line 23, in download
    return self.download_book_from_url(url)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/scribd.py", line 77, in download_book_from_url
    raise UserNotAuthorized
audiobookdl.exceptions.UserNotAuthorized

i used the unstable download here:
pip install "git+https://github.com/jo1gi/audiobook-dl.git"

**Comment by jo1gi** [comment]
You can't login with username and password. Use cookies.
