### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by escidmore** [jo1gi/audiobook-dl#38]
**Installation method:**
Same issue with pip and using setup.py from repo

**Version:**
Python: Python 3.8.10
audiobook-dl: 0.5.0

**Describe the bug**
Receive the following error any time I try to run audiobook-dl, regardless of parameters (or with no parameters at all)

**Command output**
» audiobook-dl
Traceback (most recent call last):
  File "/usr/local/bin/audiobook-dl", line 5, in <module>
    from audiobookdl.__main__ import run
  File "/usr/local/lib/python3.8/dist-packages/audiobookdl/__init__.py", line 1, in <module>
    from .utils.audiobook import AudiobookFile, Chapter, AudiobookMetadata, Cover, Audiobook
  File "/usr/local/lib/python3.8/dist-packages/audiobookdl/utils/__init__.py", line 21, in <module>
    def nearest_string(input: str, list: list[str]) -> str:
TypeError: 'type' object is not subscriptable

**Comment by jo1gi** [comment]
Looks like i use a feature in python that's first introduced in python 3.9.0. I will see what I can do about it.

**Comment by jo1gi** [comment]
Think i fixed it in [aae385d](https://github.com/jo1gi/audiobook-dl/commit/aae385d84fe79884e1be798e9a83d161f38e9f10). The changes are currently only on GitHub. Hope it works.

**Comment by jo1gi** [comment]
I can't replicate it. Have to tried uninstalling the program?

**Comment by escidmore** [comment]
I don't currently have the program installed, and just in case of some kind of change to my local copy of the GitHub repo that was causing issues I removed it and cloned it again, then re-ran "python3 setup.py install" with the same result.

**Comment by jo1gi** [comment]
I'm still not sure why it's not working, but I'll try to figure it out. Until then, try installing from pypi. I have updated it there now.
