### ISSUE TITLE
fetching metadata

### ISSUE THREAD

**Issue by evafans** [jo1gi/audiobook-dl#4]
Will the audio from scribd containing metadata(author,narrator),if it does, what is the error that I can't get it?
 File "C:\Program Files\Python39\Scripts\audiobook-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.1.0', 'console_scripts', 'audiobook-dl')())
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.1.0-py3.9.egg\audiobookdl\__main__.py", line 42, in run
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.1.0-py3.9.egg\audiobookdl\utils\service.py", line 138, in download
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.1.0-py3.9.egg\audiobookdl\utils\metadata.py", line 30, in add_metadata
  File "C:\Program Files\Python39\lib\site-packages\audiobook_dl-0.1.0-py3.9.egg\audiobookdl\utils\metadata.py", line 20, in add_id3_metadata
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by evafans** [comment]
Also,it wont download covers.

**Comment by evafans** [comment]
I tried to reinstall it,now I cant download files,dnw.

C:\Users\Administrator>audiobook-dl -c C:\audiobook-dl-master\cookies.txt https://www.scribd.com/listen/237959141
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\audiobook-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.1.0', 'console_scripts', 'audiobook-dl')())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\audiobook-dl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'audiobookdl'

**Comment by jo1gi** [comment]
I think I have fixed the bug with metadata, but it still does not download the books. Covers are currently not supported with Scribd.

**Comment by evafans** [comment]
I was able to download audio yesterday, but after I reinstalled python, it won't work, do you know what went wrong?
C:\Users\Administrator>audiobook-dl -c ‪C:\audiobook-dl-master\cookies.txt https://www.scribd.com/listen/237858757
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\audiobook-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.1.0', 'console_scripts', 'audiobook-dl')())
  File "C:\Program Files\Python39\Scripts\audiobook-dl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Program Files\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'audiobookdl'

**Comment by evafans** [comment]
the updated version has covers now,but the audio only contains chapter number,withou author and narrotor,is it unusual,or it is the way it is?

**Comment by jo1gi** [comment]
It's the way it is. I haven't implemented author and narrator for Scribd yet.

**Comment by evafans** [comment]
I think this function can be achieved, there is a isbn number to every audiobook ,using isbn you can get detailed info and cover from audible.

**Comment by thedkm** [comment]
> It's the way it is. I haven't implemented author and narrator for Scribd yet.

author is there now , Just need to Add title and album , well title==album , so getting title and adding it to file , can u add it?

**Comment by jo1gi** [comment]
I have added support for title now. I have only put it in the title tag and not the album tag, because I want the album tag to be the series if that's available. What do you think?

**Comment by thedkm** [comment]
ahh thats fine , title was must now I don't have to manually add it on each file.  

Album                       : Forty is Fabulous #04
Track name                  : Making Midlife Marvels
Performer                   : Heloise Hull
Original/Lyricist           : Heloise Hull

nice work BTW i noticed that now ffmpeg merge doesn't show any progress thats bad , can u enable it again?

**Comment by thedkm** [comment]
NotADirectoryError: [WinError 267] The directory name is invalid: 'The Devil\\u0026#39;s Choir: A Victor Lessard Thriller' 

error on this scribd orignals https://www.scribd.com/audiobook/542379701/The-Devil-s-Choir-A-Victor-Lessard-Thriller

**Comment by jo1gi** [comment]
I think I have fixed the problem, but I'm not sure. I don't run windows and it's a windows specific problem.

**Comment by thedkm** [comment]
> I think I have fixed the problem, but I'm not sure. I don't run windows and it's a windows specific problem.

Ohh ok will test it , BTW did able to merge aac files yet?

**Comment by thedkm** [comment]
i noticed that now ffmpeg merge doesn't show any progress thats bad , can u enable it again? what about this??

**Comment by jo1gi** [comment]
> i noticed that now ffmpeg merge doesn't show any progress thats bad , can u enable it again? what about this??

I can make it an option.

**Comment by thedkm** [comment]
make that option for verbose ffmpeg output .

about aac files i tried to convert all of aac files into m4b files using ffmpeg script  then tried to merge these m4bs into single m4b it worked but it takes twice as long time sadly.

**Comment by jo1gi** [comment]
I have created an new option, `--verbose-ffmpeg` 2ea824b.

**Comment by thedkm** [comment]
> I have created an new option, `--verbose-ffmpeg` [2ea824b](https://github.com/jo1gi/audiobook-dl/commit/2ea824b52fa39261ec3752eca82058191e66a26d).

Thanks
