### ISSUE TITLE
Missing dependency appdirs

### ISSUE THREAD

**Issue by joshuatly** [jo1gi/audiobook-dl#52]
**Installation method:**
*Github repo or pip/pypi*
pip

**Version:**
*Python version and audiobook-dl version*
0.6.2

**Describe the bug**
*A clear and concise description of what the bug is.*
when appdirs is not installed, it will fail at:
➜  ~ audiobook-dl --help
Traceback (most recent call last):
  File "/usr/local/bin/audiobook-dl", line 5, in <module>
    from audiobookdl.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/audiobookdl/__main__.py", line 6, in <module>
    from .config import load_config, Config
  File "/usr/local/lib/python3.9/site-packages/audiobookdl/config.py", line 7, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'

This should be fixed by including the necessary module while installing. 

**Command output**
*Command and output with `--debug` flag*

**Comment by jo1gi** [comment]
Have added it now
