### ISSUE TITLE
KeyError: 'iisbn'

### ISSUE THREAD

**Issue by mikeSwe77** [jo1gi/audiobook-dl#61]
**Installation method:**
PIP

**Version:**
Python 3.9.2
audiobook-dl 0.6.2

**Describe the bug**
Crash

**Command output**
audiobook-dl --username ****MASKED***** --password ****MASKED***** ****MASKED***** -d

DEBUG audiobook-dl 0.6.2
DEBUG python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110]
Finding compatible source
Authenticating with storytel
DEBUG Logging in
Traceback (most recent call last):
  File "/usr/local/bin/audiobook-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/audiobookdl/__main__.py", line 32, in main
    process_url(url, options, config)
  File "/usr/local/lib/python3.9/dist-packages/audiobookdl/__main__.py", line 53, in process_url
    result = source.download(url)
  File "/usr/local/lib/python3.9/dist-packages/audiobookdl/sources/storytel.py", line 67, in download
    cover = self.download_cover(book_info),
  File "/usr/local/lib/python3.9/dist-packages/audiobookdl/sources/storytel.py", line 168, in download_cover
    isbn = book_info["abook"]["iisbn"]
KeyError: 'iisbn'

Running on a Raspberry PI4B w. Raspbian bullseye

**Comment by jo1gi** [comment]
The bug is fixed in the next version of audiobook-dl. Try installing it from Github until I get it on pip.

**Comment by mikeSwe77** [comment]
Confirmed working when pulling latest version.
