### ISSUE TITLE
Support Everand

### ISSUE THREAD

**Issue by pranavmalikk** [jo1gi/audiobook-dl#63]
**Installation method:**
*Github Repo*

**Version:**
*Python 3.9.17 and audiobook-dl 0.6.2*

**Describe the bug**
*urllib.error.HTTPError: HTTP Error 400: Bad Request*

**Command output**
*DEBUG audiobook-dl 0.6.2
DEBUG python 3.9.17 (main, Jul  5 2023, 20:41:20) 
[GCC 11.2.0]
 INFO Finding compatible source
 INFO Authenticating with scribd
DEBUG Loading cookies from 'cookies-scribd-com.txt'
DEBUG 
Traceback (most recent call last):
  File "/home/kingpin/miniconda3/envs/test/bin/audiobook-dl", line 8, in <module>
    sys.exit(main())
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/__main__.py", line 32, in main
    process_url(url, options, config)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/__main__.py", line 53, in process_url
    result = source.download(url)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/scribd.py", line 23, in download
    return self.download_book_from_url(url)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/scribd.py", line 79, in download_book_from_url
    return self.download_scribd_original(book_id[:7], url)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/scribd.py", line 109, in download_scribd_original
    files = self.get_stream_files(stream_url, headers = { "Authorization": jwt }),
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/audiobookdl/sources/source/networking.py", line 50, in get_stream_files
    playlist = m3u8.load(url, headers=headers)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/m3u8/__init__.py", line 96, in load
    content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/site-packages/m3u8/httpclient.py", line 16, in download
    resource = opener.open(uri, timeout=timeout)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/kingpin/miniconda3/envs/test/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request*

here's the command:
audiobook-dl -c cookies-scribd-com.txt https://www.scribd.com/audiobook/480575478/Djinn-City

**Comment by jo1gi** [comment]
Think it is another occurrence of #54

**Comment by jo1gi** [comment]
Sorry I was wrong. Looks like Scribd is rebranding and have changed the api in the process.

**Comment by pranavmalikk** [comment]
Oh i see that everand is the new platform, I know someone who was trying to scrape these links but it seems they are encrypted? I'm not sure how it is on everand

**Comment by jo1gi** [comment]
The api is close. It shouldn't take to long to change it.

**Comment by jo1gi** [comment]
Added some basic support for Everand in 97778a44e395404397276a4e56187c71764979e8. Hope it works.

**Comment by pranavmalikk** [comment]
i'm getting this now:

DEBUG audiobook-dl 0.6.2
DEBUG python 3.9.17 (main, Jul  5 2023, 20:41:20) 
[GCC 11.2.0]
 INFO Finding compatible source
ERROR: The url you provided is not supported by audiobook-dl

Supported services are:
 • audiobooks.com
 • Blinkist
 • BookBeat
 • Chirp
 • eReolen
 • Everand
 • Libby
 • Librivox
 • Mofibo
 • Nextory
 • Overdrive
 • Podimo
 • Saxo
 • Scribd
 • Storytel
 • YourCloudLibrary
Traceback (most recent call last):
  File "/home/kingpin/audiobook-dl/audiobookdl/__main__.py", line 32, in main
    process_url(url, options, config)
  File "/home/kingpin/audiobook-dl/audiobookdl/__main__.py", line 49, in process_url
    source = find_compatible_source(url)
  File "/home/kingpin/audiobook-dl/audiobookdl/sources/__init__.py", line 28, in find_compatible_source
    raise NoSourceFound
audiobookdl.exceptions.NoSourceFound

**Comment by jo1gi** [comment]
I'm not sure what's wrong. I can't replicate it. Try quoting the url?

**Comment by pranavmalikk** [comment]
are you able to download this successfully? which way should i update the python package? i've tried quoting but no luck. 
here's my command but i'm running it through the cloning the repo:
python -m audiobookdl cookies-everand-com.txt https://www.everand.com/audiobook/480575478/Djinn-City --debug

**Comment by pranavmalikk** [comment]
I'm able to run it locally by doing this:
python -m audiobookdl -c cookies-everand-com.txt https://www.everand.com/audiobook/480575478/Djinn-City

Thanks

**Comment by adampalli** [comment]
**Installation method:**
pip install "git+https://github.com/jo1gi/audiobook-dl.git"

**Version:**
Python 3.12.0 audiobook-dl 0.6.2

**Describe the bug**
Can't Download most audiobooks from everand. 
ERROR: Missing data from source

**Command output**
Command audiobook-dl https://www.everand.com/listen/331787549 --debug
Output
DEBUG audiobook-dl 0.6.2
DEBUG python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
 INFO Finding compatible source
 INFO Authenticating with everand
DEBUG Loading cookies from './cookies.txt'
DEBUG csrf={'csrf_token': 'Redacted'}
DEBUG Could not find match from https://www.everand.com/listen/331787549 with (?<=("jwt_token":\{"token":"))[^"]+
ERROR: Missing data from source

audiobook-dl is missing data from source. This can happen when you try to
download audiobooks you don't have access too (not logged in or your profile
doesn't have the right permissions), the site has been updated and audiobook-dl
hasn't implemented the new version, or it could be a bug in audiobook-dl.

If you think it is a problem with audiobook-dl please create an issue at
https://github.com/jo1gi/audiobook-dl/issues
Traceback (most recent call last):
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 32, in main
    process_url(url, options, config)
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 53, in process_url
    result = source.download(url)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\everand.py", line 24, in download
    return self.download_book_from_url(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\everand.py", line 83, in download_book_from_url
    jwt = self.find_in_page(url, r'(?<=("jwt_token":\{"token":"))[^"]+')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mypc\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\source\__init__.py", line 147, in find_in_page
    raise DataNotPresent
audiobookdl.exceptions.DataNotPresent

**Comment by cerinawithasea** [comment]
IM not sure if this is me or a bug (was the first time I tried to use it) 
I just found this and installed for everand and i didn't know where to go to ask


C:\Users\Cerina>audiobook-dl -c C:\Users\Cerina\Documents\www.everand.com_cookies.txt https://www.everand.com/listen/638140573
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Scripts\audiobook-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 6, in <module>
    from .config import load_config, Config
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\config.py", line 7, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'



I just hated the thought of banging my head against a wall for the next 6 hours trying to figure it out and it not be me (it happens sometimes *once)
I really hope it me 
Thanks

**Comment by jo1gi** [comment]
@cerinawithasea Looks like you don't have appdirs installed. It can be fixed with `pip install appdirs`. Make sure you install audiobook-dl from Github, if you want Everand support. It is not on pypi yet.

**Comment by cerinawithasea** [comment]
Oh my gosh thank you so much, i just pulled that whole comment down assuming it had to be me
this helps loads

**Comment by cerinawithasea** [comment]
Hi thanks that all worked perfect, do you have a quick setting to get me past the 5712 files for one book? I am assuming this is the crazy way they have most of the books now, is there an argument i need to add?
Im sorry im in this bug asking, im not well versed on github and i had used z3kit until now
I appreciate your time and i tried to support the project a little (i hope)

**Comment by jo1gi** [comment]
You can use `--combine` to create a single file. It requires ffmpeg to be installed. It is currenyly a bit buggy.

**Comment by cerinawithasea** [comment]
Thanks , i think i spoke to soon tho  (i did not try to combine yet)

C:\Users\Cerina>audiobook-dl -c C:\Users\Cerina\Documents\www.everand.com_cookies.txt https://www.everand.com/listen/677189008
Finding compatible source
Authenticating with everand
Traceback (most recent call last):
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 32, in main
    process_url(url, options, config)
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 53, in process_url
    result = source.download(url)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\everand.py", line 24, in download
    return self.download_book_from_url(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\everand.py", line 83, in download_book_from_url
    jwt = self.find_in_page(url, r'(?<=("jwt_token":\{"token":"))[^"]+')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\source\__init__.py", line 147, in find_in_page
    raise DataNotPresent
audiobookdl.exceptions.DataNotPresent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Scripts\audiobook-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 34, in main
    e.print()
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\exceptions.py", line 12, in print
    print_error_file(self.error_description, **self.data)
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\logging.py", line 49, in print_error_file
    msg = read_asset_file(f"assets/errors/{name}.txt").format(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\utils\__init__.py", line 34, in read_asset_file
    .read_text(encoding="utf8")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1028, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cerina\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1014, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Cerina\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\audiobookdl\\assets\\errors\\data_not_present.txt'

Last i will bother you for today, i promise, and i appreciate you

**Comment by jo1gi** [comment]
@adampalli Think the new version on Github should fix that problem.

**Comment by jo1gi** [comment]
@adampalli @cerinawithasea Does it work?

**Comment by adampalli** [comment]
> @adampalli @cerinawithasea Does it work?

Yes, it does work for most cases. Thanks for the support. But at times, I get the following error. 
FileNotFoundError: [WinError 206] The filename or extension is too long

Example link: https://www.everand.com/audiobook/538138488/Outsmart-Your-Brain-Unexpected-Hacks-to-Boost-Your-Productivity

**Comment by jo1gi** [comment]
@adampalli You can use `--output` to change the output location.

**Comment by adampalli** [comment]
Can you please explain how to use --output command to overcome The filename or extension is too long error?

**Comment by Morghain** [comment]
any updates on the file to long error? 
I tried --output and given the shortest location name possible, but it keeps giving the same error

**Comment by jo1gi** [comment]
@adampalli Have you tried with `--output short_name`?

**Comment by adampalli** [comment]
> --output short_name

Now I've tried it and it works! No more The filename or extension is too long error. Thanks for the clarity :)
