### ISSUE TITLE
Everand downloading 1000s of files and --combine doesn't work

### ISSUE THREAD

**Issue by jaegercoder** [jo1gi/audiobook-dl#68]
**Installation method:**
Github repo

**Version:**
audiobook-dl 0.7.0
Python 3.10.12

**Describe the bug**
Everand option downloads 1000s of aac files which I am not able to combine.

The` --combine` option only converts the first file and leave all others

**Command output**

`audiobook-dl --combine --output-format m4b --verbose-ffmpeg`

```
    Metadata:
    encoder         : Lavf58.76.100
    major_brand     : M4A 
    minor_version   : 512
    compatible_brands: M4A isomiso2
  Duration: 00:00:05.02, start: 0.000000, bitrate: 26378 kb/s
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 80 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output #0, ipod, to 'The Prez/output_file.m4b':
  Metadata:
    compatible_brands: M4A isomiso2
    major_brand     : M4A 
    minor_version   : 512
    encoder         : Lavf58.76.100
  Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 80 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=      51kB time=00:00:04.99 bitrate=  83.4kbits/s speed=8.93e+03x    
video:0kB audio:49kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.324402%
  Adding metadata
  Embedding cover
```

**Comment by jo1gi** [comment]
This commit fixed it for me. Does it work for you?

**Comment by JaegerMaster** [comment]
Well, I think that issue is resolved @jo1gi . However now I get a ffmpeg error.

```
Traceback (most recent call last):
  File "/home/jaeger/.local/bin/audiobook-dl", line 8, in <module>
    sys.exit(main())
  File "/home/jaeger/.local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 32, in main
    process_url(url, options, config)
  File "/home/jaeger/.local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 58, in process_url
    process_audiobook(result, options)
  File "/home/jaeger/.local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 163, in process_audiobook
    download(audiobook, options)
  File "/home/jaeger/.local/lib/python3.10/site-packages/audiobookdl/output/download.py", line 37, in download
    download_audiobook(audiobook, output_dir, options)
  File "/home/jaeger/.local/lib/python3.10/site-packages/audiobookdl/output/download.py", line 54, in download_audiobook
    output.combine_audiofiles(filepaths, output_dir, output_path)
  File "/home/jaeger/.local/lib/python3.10/site-packages/audiobookdl/output/output.py", line 39, in combine_audiofiles
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'ffmpeg'
```

**Comment by jo1gi** [comment]
@JaegerMaster What book is it?

**Comment by jaegercoder** [comment]
@jo1gi 

This is one of the books that didn't work. 
https://www.everand.com/audiobook/638828556/The-Awakened-Ape-A-Biohacker-s-Guide-to-Evolutionary-Fitness-Natural-Ecstasy-and-Stress-Free-Living

**Comment by JaegerMaster** [comment]
@jo1gi Still Not working

audiobook-dl -c ~/scripts/cookies.txt --combine -f mp3 https://www.everand.com/audiobook/683386581/A-Brilliant-Life-My-Mother-s-Inspiring-True-Story-of-Surviving-the-Holocaust

Output File details:
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 08:50     MPEG1, Layer III        [ 56 kb/s @ 44100 Hz - Mono ]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ID3 v2.4:
title: A Brilliant Life: My Mother’s Inspiring True Story of Surviving the Holocaust
artist: Rachelle Unreich
album:
track:
UserTextFrame: [Description: PERFORMER]
Rachel Griffiths
OTHER Image: [Size: 52140 bytes] [Type: image/jpeg]
Description:
```

**Comment by jo1gi** [comment]
@JaegerMaster Weird. I have no problem downloading that book.

**Comment by jaegercoder** [comment]
@jo1gi What is the ffmpeg version you are using mine is 4.4.2

Some of the books work and some don't

For eg:
https://www.everand.com/audiobook/374354831/Ask-a-North-Korean-Defectors-Talk-About-Their-Lives-Inside-the-World-s-Most-Secretive-Nation: Works
https://www.everand.com/audiobook/683386581/A-Brilliant-Life-My-Mother-s-Inspiring-True-Story-of-Surviving-the-Holocaust: Doesn't work

**Comment by jo1gi** [comment]
I use ffmpeg 5.1.3 and I don't have any problems with A Brilliant Life.

**Comment by JaegerMaster** [comment]
Changed my ffmpeg to 6 and works now. Must be an ffmpeg issue. Maybe you may want to indicate a minimum ffmpeg version @jo1gi

**Comment by ebal99** [comment]
@jo1gi I am having issues with this and any book that downloads using the hundreds of AAC files is not working for me.  I have the latest version of Audioboo-dl, FFMPEG v6, and Python 3.9.  The files download but when trying to combine them it errors out. 

Any suggestions would be appreciated.  

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/XXXXXXXXXX/Desktop/TheSilmarillion/output_file.aac' -> '/Users/XXXXXXXXXXX/Desktop/TheSilmarillion/input_file.aac'

**Comment by Graywaren** [comment]
I am also having this issue, or a similar one, or I'm just doing something wrong? 12668 files for one book!!! Combine not working. I get `[WinError 206] The filename or extension is too long`. I'd really like to download 10+ books, but I don't want to have to deal with 10,000s files later. Here's the log:

`C:\Users\Ronan>audiobook-dl -cD:\Ronan\Books\audiobook-dl-files\cookies\everand-cookies.txt -oD:\Ronan\Books\audiobook-dl-files\outputs\{title} --combine --verbose-ffmpeg http://www.everand.com/listen/638079282
Finding compatible source
Authenticating with everand

Downloading Between Family from everand
  Creating output dir
  Downloading Between Family ---------------------------------------- 100%
  Combining files
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Scripts\audiobook-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 31, in main
    process_url(url, options, config)
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 58, in process_url
    process_audiobook(result, options)
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 163, in process_audiobook
    download(audiobook, options)
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\output\download.py", line 37, in download
    download_audiobook(audiobook, output_dir, options)
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\output\download.py", line 54, in download_audiobook
    output.combine_audiofiles(filepaths, output_dir, output_path)
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\output\output.py", line 39, in combine_audiofiles
    subprocess.run(
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 206] The filename or extension is too long`
