### ISSUE TITLE
Requestiong to add Hoopla Digital

### ISSUE THREAD

**Issue by Amraan-Amjad** [jo1gi/audiobook-dl#70]
Hello,

I am requesting to add Hoopla Digital to this script
Hoopla Digital is a web and mobile library media streaming platform launched in 2010 for audio books, comics, e-books, movies, music, and TV. Patrons of a library that supports Hoopla have access to its collection of digital media

Unlike Libby, Hoopla Digital is hold-free which means that there are no holds

You may know that Libby has long waiting queues of holds ranging even 2 months long

Hoopla doesn't have this problem, there are unlimited copies of each book

If you can somehow add Hoopla Digital to the extension it would be wonderful
If you don't have Hoopla let me know & I will share with you my credentials

Hoping for support from your side,
Tokyo2020

**Comment by jo1gi** [comment]
I'm willing to try to add it, but I don't have an account. Could you send your credentials to joakimholm@protonmail.com?

**Comment by Amraan-Amjad** [comment]
> I'm willing to try to add it, but I don't have an account. Could you send your credentials to [joakimholm@protonmail.com](mailto:joakimholm@protonmail.com)?

@jo1gi Sent

**Comment by Amraan-Amjad** [comment]
@jo1gi 
Thanks for your mail
& I have sent you one too
Could check this & tell me where I am getting anything wrong

**Comment by Amraan-Amjad** [comment]
https://github.com/larsenv/Hoopla-Digital-Downloader
This might help
@jo1gi

**Comment by 3052** [comment]
> https://github.com/larsenv/Hoopla-Digital-Downloader This might help @jo1gi

dead link

**Comment by devnoname120** [comment]
@3052 https://web.archive.org/web/20240308205132/https://codeload.github.com/larsenv/Hoopla-Digital-Downloader/zip/refs/heads/main

**Comment by 3052** [comment]
I gave up on Hoopla because their quality is dogshit

width="640" height="360"

**Comment by devnoname120** [comment]
Even with Widevine L1?

**Comment by 3052** [comment]
I dont have L1 or know where to get it

**Comment by ladle3000** [comment]
> I gave up on Hoopla because their quality is dogshit
> 
> width="640" height="360"

Any chance you might revisit this? This and Libby are the only 2 services our library includes and they tend to have more audiobooks I'm after than Libby.

**Comment by 3052** [comment]
eh I posted here in error because I only care about movies/TV not audio books

**Comment by eastoncrafter** [comment]
[hoopladownloader.zip](https://github.com/user-attachments/files/18295758/hoopladownloader.zip)
Had some issues running on windows, made some modifications to get it to work

**Comment by carrerare7** [comment]
> [hoopladownloader.zip](https://github.com/user-attachments/files/18295758/hoopladownloader.zip) Had some issues running on windows, made some modifications to get it to work

Thanks, I just tried and I get the following error: 1 files have been moved.
The file name, directory name, or volume label syntax is incorrect.C:\Users\RICK\Downloads\hoopladownloader\Input.mp4 could not be found
Could not find C:\Users\RICK\Downloads\hoopladownloader\Output.mp4

I took the liberty and sent you an email to the email you left in one of your repositories, maybe if it's not too much trouble you could help me (when you see the email you will understand me), thank you.

**Comment by eastoncrafter** [comment]
[hoopladownloaderng.zip](https://github.com/user-attachments/files/18308951/hoopladownloaderng.zip)
Made a batch script and did all the libraries with a venv and stuff so hopefully that fixes some stuff. Should also place downloads in the FINISHED folder now. don't worry about any of the couldn't find stuff, the rest should still work. If you have any more questions you could email me at valiantroku@gmail.com. Not sure which email you sent to, since I don't usually put my emails in github..

**Comment by carrerare7** [comment]
Thanks, I just tried it and I got this error (by the way I left you an email)

[download] 100% of 300.78MiB in 00:04:17 at 1.17MiB/s
1 files have been moved.
The file name, directory name or syntax of the volume label is not correct.C:\Users could not find C:\RICK\Desktoptop\hoopladownloaderng\Input.mp4
C:\Users could not find C:\RICK\RICK\Desktop\hoopladownloadloaderng\Output.mp4
Press a key to continue . . .

**Comment by carrerare7** [comment]
> [hoopladownloaderng.zip](https://github.com/user-attachments/files/18308951/hoopladownloaderng.zip) Made a batch script and did all the libraries with a venv and stuff so hopefully that fixes some stuff. Should also place downloads in the FINISHED folder now. don't worry about any of the couldn't find stuff, the rest should still work. If you have any more questions you could email me at [valiantroku@gmail.com](mailto:valiantroku@gmail.com). Not sure which email you sent to, since I don't usually put my emails in github..

Thanks, I just tried it and I got this error (by the way I left you an email)

[download] 100% of 300.78MiB in 00:04:17 at 1.17MiB/s
1 files have been moved.
The file name, directory name or syntax of the volume label is not correct.C:\Users could not find C:\RICK\Desktoptop\hoopladownloaderng\Input.mp4
C:\Users could not find C:\RICK\RICK\Desktop\hoopladownloadloaderng\Output.mp4
Press a key to continue . . .

**Comment by slgsuraj** [comment]
> [hoopladownloader.zip](https://github.com/user-attachments/files/18295758/hoopladownloader.zip) Had some issues running on windows, made some modifications to get it to work

Traceback (most recent call last):
  File "C:\Users\User\Downloads\New folder\NEW RELEASE\hoopladownloader\l3.py", line 14, in <module>
    import pyperclip
ModuleNotFoundError: No module named 'pyperclip'
Traceback (most recent call last):
  File "C:\Users\User\Downloads\New folder\NEW RELEASE\hoopladownloader\hoopla-key.py", line 85, in <module>
    print(url + ": " + title + ": " + "--key " + response.split("--key ")[1])
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by carrerare7** [comment]
> > [hoopladownloader.zip](https://github.com/user-attachments/files/18295758/hoopladownloader.zip) Tuve algunos problemas al ejecutarme en Windows, hice algunas modificaciones para que funcionara
> 
> ¿Qué estoy haciendo mal?
> 
> Rastreo (última llamada más reciente): Archivo "C:\Users\User\Downloads\New folder\NEW RELEASE\hoopladownloader\l3.py", línea 14, en import pyperclip ModuleNotFoundError: No hay módulo llamado 'pyperclip' Traceback (última llamada más reciente): Archivo "C:\Users\User\Downloads\New folder\NEW RELEASE\hoopladownloader\hoopla-key.py", línea 85, en print(url + ": " + title + ": " + "--key " + response.split("--key ")[1]) ~~~~~~~~~~~~~~~~~~~~~~~~^^^ IndexError: índice de la lista fuera de rango

In the zip there is a txt that says this

Just make sure to run this: pip install --upgrade protobuf==3.20.3
and everything should be fixed

I don't know if that would help you

**Comment by eastoncrafter** [comment]
@slgsuraj Looks like the DRM script is failing for one reason or another. The latest zip included a virtual environment will all the libraries needed, please try that one (the one ending in ng.zip) and let me know how it goes!

**Comment by eastoncrafter** [comment]
Note that anytime someone gets an error like below, it usually means the function used to grab the DRM keys has failed for one reason or another. 

File "C:\Users\User\Downloads\New folder\NEW RELEASE\hoopladownloader\hoopla-key.py", line 85, in
print(url + ": " + title + ": " + "--key " + response.split("--key ")[1])
~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by abidxraihan** [comment]
@eastoncrafter I just wanted to thank you. [hoopladownloaderng.zip](https://github.com/user-attachments/files/18308951/hoopladownloaderng.zip) worked flawlessly.

**Comment by slgsuraj** [comment]
Reason Behind this? [file is not getting move to finished location]


If you experience any issues while using this option, DO NOT open a bug report
[generic] Extracting URL: https://dash.hoopladigital.com/pod_9781039496606/Manifest.mpd
[generic] Manifest: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Manifest: Extracting information
[info] Manifest: Downloading 1 format(s): 0
[download] Destination: Manifest [Manifest].m4a
[download] 100% of  456.33MiB in 00:01:55 at 3.95MiB/s
        1 file(s) moved.
The filename, directory name, or volume label syntax is incorrect.
        0 file(s) moved.
Could Not Find C:\Users\Asus\Downloads\New Release\hoopladownloaderng\Input.mp4
Could Not Find C:\Users\Asus\Downloads\New Release\hoopladownloaderng\Output.mp4

**Comment by ladle3000** [comment]
Sorry, but how do we enable for hoopla? What are the directions?

Thank you,
-scott

Sent with Proton encrypted email service.

**Comment by eastoncrafter** [comment]
Currently, I was able to get things working, but I'm not sure how I'd integrate it into audiobook-dl yet. I can create a repository with this if people are interested?

Also, @slgsuraj

> Reason Behind this? [file is not getting move to finished location]
> 
> If you experience any issues while using this option, DO NOT open a bug report [generic] Extracting URL: https://dash.hoopladigital.com/pod_978103something/Manifest.mpd [generic] Manifest: Downloading webpage WARNING: [generic] Falling back on generic information extractor [generic] Manifest: Extracting information [info] Manifest: Downloading 1 format(s): 0 [download] Destination: Manifest [Manifest].m4a [download] 100% of 456.33MiB in 00:01:55 at 3.95MiB/s 1 file(s) moved. The filename, directory name, or volume label syntax is incorrect. 0 file(s) moved. Could Not Find C:\Users\Asus\Downloads\New Release\hoopladownloaderng\Input.mp4 Could Not Find C:\Users\Asus\Downloads\New Release\hoopladownloaderng\Output.mp4

Looks like it's just a cleanup error, everything should be downloaded. I think it depends on which format the audiobook comes in. I'll investigate silencing the failed commands since it's not really anything important

**Comment by slgsuraj** [comment]
> Currently, I was able to get things working, but I'm not sure how I'd integrate it into audiobook-dl yet. I can create a repository with this if people are interested?
> 
> Also, [@slgsuraj](https://github.com/slgsuraj)
> 
> > Reason Behind this? [file is not getting move to finished location]
> > If you experience any issues while using this option, DO NOT open a bug report [generic] Extracting URL: https://dash.hoopladigital.com/pod_978103something/Manifest.mpd [generic] Manifest: Downloading webpage WARNING: [generic] Falling back on generic information extractor [generic] Manifest: Extracting information [info] Manifest: Downloading 1 format(s): 0 [download] Destination: Manifest [Manifest].m4a [download] 100% of 456.33MiB in 00:01:55 at 3.95MiB/s 1 file(s) moved. The filename, directory name, or volume label syntax is incorrect. 0 file(s) moved. Could Not Find C:\Users\Asus\Downloads\New Release\hoopladownloaderng\Input.mp4 Could Not Find C:\Users\Asus\Downloads\New Release\hoopladownloaderng\Output.mp4
> 
> Looks like it's just a cleanup error, everything should be downloaded. I think it depends on which format the audiobook comes in. I'll investigate silencing the failed commands since it's not really anything important

Okay Thank you... Is there a method to convert an m4a file into an m4b format while adding chapters?

**Comment by slgsuraj** [comment]
> Currently, I was able to get things working, but I'm not sure how I'd integrate it into audiobook-dl yet. I can create a repository with this if people are interested?
> 
> Also, [@slgsuraj](https://github.com/slgsuraj)
> 
> > Reason Behind this? [file is not getting move to finished location]
> > If you experience any issues while using this option, DO NOT open a bug report [generic] Extracting URL: https://dash.hoopladigital.com/pod_978103something/Manifest.mpd [generic] Manifest: Downloading webpage WARNING: [generic] Falling back on generic information extractor [generic] Manifest: Extracting information [info] Manifest: Downloading 1 format(s): 0 [download] Destination: Manifest [Manifest].m4a [download] 100% of 456.33MiB in 00:01:55 at 3.95MiB/s 1 file(s) moved. The filename, directory name, or volume label syntax is incorrect. 0 file(s) moved. Could Not Find C:\Users\Asus\Downloads\New Release\hoopladownloaderng\Input.mp4 Could Not Find C:\Users\Asus\Downloads\New Release\hoopladownloaderng\Output.mp4
> 
> Looks like it's just a cleanup error, everything should be downloaded. I think it depends on which format the audiobook comes in. I'll investigate silencing the failed commands since it's not really anything important

@eastoncrafter Thank you for the reply... One Question... Is there a method to convert an m4a file into an m4b format while adding chapters?

**Comment by abidxraihan** [comment]
@slgsuraj  
> .. Is there a method to convert an m4a file into an m4b format while adding chapters?

I use [Chapters and Verse](http://lodensoftware.com/downloads/) or [AudioBookConverter](https://github.com/yermak/AudioBookConverter).

**Comment by slgsuraj** [comment]
C:\Users\Asus\Downloads\New Release\Script\hoopladownloaderng>python hoopla-key.py https://www.hoopladigital.com/audiobook/beyond-the-aching-door-victoria-mier/17709804 eyJ1c2VySWQiOjE0MTM5ODI4LsomethinguSWQiOiI0MDY5MTk1NDciLCJtZXJjaGFudCI6something
Hoopla Digital Downloader by Larsenv

https://dash.hoopladigital.com/ttm_9798855571332/Manifest.mpd
pssh=AAAAOHBzc2gAAAAA7e+LqXnsomethingQAAABgSEEgyqhpyWEZXnvJtuU/o5XJI49yVmwY=
Traceback (most recent call last):
  File "C:\Users\Asus\Downloads\New Release\Script\hoopladownloaderng\l3.py", line 15, in <module>
    from pywidevine.L3.cdm import cdm, deviceconfig
ModuleNotFoundError: No module named 'pywidevine.L3'
Traceback (most recent call last):
  File "C:\Users\Asus\Downloads\New Release\Script\hoopladownloaderng\hoopla-key.py", line 86, in <module>
    print(url + ": " + title + ": " + "--key " + response.split("--key ")[1])
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range


Any solution?

**Comment by eastoncrafter** [comment]
Unfortunately, HOOPLA has DMCA'd this downloader and doesn't want it public. I've been forced to remove it, or face termination of my GitHub account. Apologies. 12/4/2025. Taking this into account I believe including it into audiobook-dl will be impossible.
