### ISSUE TITLE
Everand - Missing data from source error 

### ISSUE THREAD

**Issue by ForcedComedy** [jo1gi/audiobook-dl#71]
**Installation method:**
pip

**Version:**
python 3.12.0

**Describe the bug**
Missing data from source error 

**Command output**
DEBUG audiobook-dl 0.7.1
DEBUG python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]

![image](https://github.com/jo1gi/audiobook-dl/assets/135008884/21cebd83-9284-4970-80b6-105dc58a69be)

**Comment by jo1gi** [comment]
I'm not sure whats wrong yet, but I got it working with the version on Github.

**Comment by kauesena** [comment]
Any news? I am having the same problem.

**Comment by kauesena** [comment]
Hi, @jo1gi. Thank you for the help. Here is the output:
```zsh
(.venv) :: ~ » audiobook-dl -c cookies-everand-com.txt https://www.everand.com/audiobook/638620660/Are-Prisons-Obsolete --debug
DEBUG audiobook-dl 0.7.2
DEBUG python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
INFO Finding compatible source
INFO Authenticating with everand
DEBUG Loading cookies from 'cookies-everand-com.txt'
DEBUG Downloading result of https://www.everand.com/audiobook/638620660/Are-Prisons-Obsolete
DEBUG Could not find match from https://www.everand.com/listen/638620660 with (?<=(Scribd.Audiobooks.Show, 
)){.+}(?=\))
ERROR: Missing data from source

audiobook-dl is missing data from source. This can happen when you try to
download audiobooks you don't have access too (not logged in or your profile
doesn't have the right permissions), the site has been updated and audiobook-dl
hasn't implemented the new version, or it could be a bug in audiobook-dl.

If you think it is a problem with audiobook-dl please create an issue at
https://github.com/jo1gi/audiobook-dl/issues

Traceback
Traceback (most recent call last):
File "/home/user1/audiobook-dl/.venv/lib/python3.11/site-packages/audiobookdl/__main__.py", line 31, in main
process_url(url, options, config)
File "/home/user1/audiobook-dl/.venv/lib/python3.11/site-packages/audiobookdl/__main__.py", line 54, in process_url
result = source.download(url)
^^^^^^^^^^^^^^^^^^^^
File "/home/user1/audiobook-dl/.venv/lib/python3.11/site-packages/audiobookdl/sources/everand.py", line 24, in download
return self.download_book_from_url(url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user1/audiobook-dl/.venv/lib/python3.11/site-packages/audiobookdl/sources/everand.py", line 77, in download_book_from_url
book_info = self.extract_info(url)
^^^^^^^^^^^^^^^^^^^^^^
File "/home/user1/audiobook-dl/.venv/lib/python3.11/site-packages/audiobookdl/sources/everand.py", line 100, in extract_info
raw = self.find_in_page(
^^^^^^^^^^^^^^^^^^
File "/home/user1/audiobook-dl/.venv/lib/python3.11/site-packages/audiobookdl/sources/source/__init__.py", line 147, in find_in_page
raise DataNotPresent
audiobookdl.exceptions.DataNotPresent
```

**Comment by jo1gi** [comment]
@kauesena I can't replicate the problem. Are you sure you are logged in? Do you have problems with other books?

**Comment by santipangastuti** [comment]
Hi @jo1gi I also have the same issue. exactly the same output as @kauesena. can help? thank you

**Comment by santipangastuti** [comment]
@ForcedComedy @kauesena I got the same issue and it's resolved for me. you need to click on 'listen now', save the cookies then paste the url (not the listen one)

**Comment by santipangastuti** [comment]
@jo1gi somehow the method above no longer worked. debugging shows the similar result as sent by @kauesena . please help, thanks!

**Comment by reskino** [comment]
PS C:\Users\user1\venv\python39\Lib\site-packages\audiobook-dl-master> audiobook-dl -c cookies.txt https://www.everand.com/listen/708794215?_gl=1*68ob96*_gcl_au*MTIwNzU4MjgxLjE3MjExMzEzNzc.
Finding compatible source
Authenticating with everand
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user1\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user1\venv\python39\Scripts\audiobook-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\__main__.py", line 31, in main
    process_url(url, options, config)
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\__main__.py", line 54, in process_url
    result = source.download(url)
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\sources\everand.py", line 24, in download
    return self.download_book_from_url(url)
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\sources\everand.py", line 78, in download_book_from_url
    files = self.get_files(book_info),
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\sources\everand.py", line 105, in get_files
    return self.get_internal_files(book_info)
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\sources\everand.py", line 119, in get_internal_files
    return self.get_stream_files(
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\sources\source\networking.py", line 62, in get_stream_files
    key = self._get_page(seg.key.absolute_uri, headers=headers),
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\sources\source\__init__.py", line 103, in _get_page
    resp = self.get(url, **kwargs)
  File "c:\users\user1\venv\python39\lib\site-packages\audiobookdl\sources\source\networking.py", line 29, in get
    resp = self._session.get(url, **kwargs)
  File "c:\users\user1\venv\python39\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "c:\users\user1\venv\python39\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\user1\venv\python39\lib\site-packages\requests\sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\users\user1\venv\python39\lib\site-packages\requests\sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'skd://drmtoday?keyId=69c10263-2925-4ef5-1868-3e556d135b3e'

**Comment by reskino** [comment]
please help i get this : No connection adapters were found for 'skd://drmtoday?keyId=69c10263-2925-4ef5-1868-3e556d135b3e'

**Comment by devnoname120** [comment]
See here to manually download and decrypt the audiobooks with the new protection: https://github.com/jo1gi/audiobook-dl/issues/129#issuecomment-2395413515
