### ISSUE TITLE
getting error in new version

### ISSUE THREAD

**Issue by jaan143** [jo1gi/audiobook-dl#8]
i uninstalled old audiobook dl version and download your new project then i installed again audiobook dl but i am getting this error evan i have installed successfully this Crypto file

PS C:\Users\Hp\Downloads\Compressed\audiobook-dl-master_7\audiobook-dl-master> audiobook-dl -c C:\cookies.txt https://www.scribd.com/listen/377204561
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\Scripts\audiobook-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.1.0', 'console_scripts', 'audiobook-dl')())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\Scripts\audiobook-dl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\audiobook_dl-0.1.0-py3.10.egg\audiobookdl\__main__.py", line 2, in <module>
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\audiobook_dl-0.1.0-py3.10.egg\audiobookdl\sources\__init__.py", line 1, in <module>
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\audiobook_dl-0.1.0-py3.10.egg\audiobookdl\sources\sources.py", line 1, in <module>
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\audiobook_dl-0.1.0-py3.10.egg\audiobookdl\sources\scribd.py", line 1, in <module>
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\audiobook_dl-0.1.0-py3.10.egg\audiobookdl\utils\source.py", line 3, in <module>
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\audiobook_dl-0.1.0-py3.10.egg\audiobookdl\utils\downloadthread.py", line 3, in <module>
ModuleNotFoundError: No module named 'Crypto'
PS C:\Users\Hp\Downloads\Compressed\audiobook-dl-master_7\audiobook-dl-master>

**Comment by jaan143** [comment]
problem solved
