### ISSUE TITLE
JSON error with Blinkist

### ISSUE THREAD

**Issue by mdleung** [jo1gi/audiobook-dl#85]
**Installation method:**
Github Repo

**Version:**
Python 3.12.1
audiobook-dl 0.7.2

**Describe the bug**
Error when trying to download a book.
See below.

**Command output**
DEBUG audiobook-dl 0.7.2
DEBUG python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
 INFO Finding compatible source
 INFO Authenticating with blinkist
DEBUG Loading cookies from 'C:\Users\matt\Downloads\cookies.txt'
DEBUG Downloading result of https://www.blinkist.com/en/nc/reader/phantoms-in-the-brain-en
Traceback (most recent call last):
  File "C:\Users\matt\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matt\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matt\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matt\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\matt\AppData\Local\Programs\Python\Python312\Scripts\audiobook-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\matt\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 31, in main
    process_url(url, options, config)
  File "C:\Users\matt\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 54, in process_url
    result = source.download(url)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matt\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\blinkist.py", line 18, in download

**Comment by jo1gi** [comment]
@mdleung I don't have an account for Blinkist. Can I borrow your account for testing?

**Comment by mdleung** [comment]
> @mdleung I don't have an account for Blinkist. Can I borrow your account for testing?

I created a trial account. Lasts for 7 days.
