### ISSUE TITLE
attrs module not found

### ISSUE THREAD

**Issue by OABiblicalHebrew** [jo1gi/audiobook-dl#88]
**Installation method:**
*Github repo or pip/pypi*
pip

**Version:**
*Python version and audiobook-dl version*
python 3.8.10
latest audiobook-dl

**Describe the bug**
*A clear and concise description of what the bug is.*

**Command output**
*Command and output with `--debug` flag*

Traceback (most recent call last):

  File "/home/andrew/.local/bin/audiobook-dl", line 5, in <module>

    from audiobookdl.__main__ import main

  File "/home/andrew/.local/lib/python3.10/site-packages/audiobookdl/__init__.py", line 1, in <module>

    from .utils.audiobook import AudiobookFile, Chapter, AudiobookMetadata, Cover, Audiobook, Result, Series, BookId

  File "/home/andrew/.local/lib/python3.10/site-packages/audiobookdl/utils/audiobook.py", line 5, in <module>

    from attrs import define, Factory

ModuleNotFoundError: No module named 'attrs'

**Comment by OABiblicalHebrew** [comment]
I ran that and got a requirement already met
