### ISSUE TITLE
Nextory KeyError: 'product_lists'

### ISSUE THREAD

**Issue by jaferb** [jo1gi/audiobook-dl#89]
**Installation method:**
*Github repo or pip/pypi*

**Version:**
*Python version and audiobook-dl version*

**Describe the bug**
*A clear and concise description of what the bug is.*

**Command output**
*Command and output with `--debug` flag*

**Comment by jo1gi** [comment]
Could you give some more details?

**Comment by jvanderkroon** [comment]
Installation method:
pip

Version:
python 3.10.9 / audiobook-dl 0.7.3

Describe the bug
Download is not starting it gives the error KeyError: 'product_lists'

Command output
audiobook-dl --username username --password password https://nextory.com/nl/book/atlas-het-verhaal-van-pa-salt-3136706 -d

```
DEBUG audiobook-dl 0.7.3
DEBUG python 3.10.9 (main, Dec 15 2022, 18:25:35) [Clang 14.0.0 
(clang-1400.0.29.202)]
 INFO Finding compatible source
 INFO Authenticating with nextory
DEBUG Logging in
DEBUG device_id='secret'
DEBUG session_response={'id': secret, 'email': 'secret',
'country': 'NL', 'emailable': True, 'sign_in_count': 6, 'phone_number': '', 
'accept_newsletter': False, 'accept_push': True, 'user_type': 'MEMBER', 
'first_name': None, 'last_name': None, 'channel': 'WEB', 'user_sub_states': [], 
'referral_url': 
'https://www.nextory.com/nl/recommend-generic-nl?utm_campaign=NX+App+%7C+Setting
s+%7C+Generic+%7C+NXNL&utm_medium=Referral&utm_source=NX+App&utm_content=skg1pNG
ZjZggBVxKQxCNmQ==', 'settings': {'pincode_enabled': False}, 'time_limit_info': 
None, 'total_consumption_secs': 652, 'override_fair_usage_policy': False, 
'is_free_trial': False, 'apple_inapp_allowed': False, 'enable_pay_now': False, 
'login_token': 
'secret'}
DEBUG 
profile_token='secret'
DEBUG Downloading result of 
https://nextory.com/nl/book/atlas-het-verhaal-van-pa-salt-3136706
Traceback (most recent call last):
  File "/usr/local/bin/audiobook-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 31, in main
    process_url(url, options, config)
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 54, in process_url
    result = source.download(url)
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/sources/nextory.py", line 93, in download
    want_to_read_list = self.download_want_to_read_list()
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/sources/nextory.py", line 135, in download_want_to_read_list
    want_to_read_id = self.download_want_to_read_id()
  File "/usr/local/lib/python3.10/site-packages/audiobookdl/sources/nextory.py", line 121, in download_want_to_read_id
    products_lists = self._session.get(
KeyError: 'product_lists'
```

**Comment by nianhbg** [comment]
I got same error
Insallation: pip
version 0.7.3

Output:
`audiobook-dl https://nextory.com/book/glasmannen-3131781
Finding compatible source
Authenticating with nextory
Username: <username>
Password:  <passord>
Traceback (most recent call last):
  File "/home/nicklas/audiobook-dl/venv/bin/audiobook-dl", line 8, in <module>
    sys.exit(main())
  File "/home/nicklas/audiobook-dl/venv/lib/python3.10/site-packages/audiobookdl/__main__.py", line 31, in main
    process_url(url, options, config)
  File "/home/nicklas/audiobook-dl/venv/lib/python3.10/site-packages/audiobookdl/__main__.py", line 54, in process_url
    result = source.download(url)
  File "/home/nicklas/audiobook-dl/venv/lib/python3.10/site-packages/audiobookdl/sources/nextory.py", line 93, in download
    want_to_read_list = self.download_want_to_read_list()
  File "/home/nicklas/audiobook-dl/venv/lib/python3.10/site-packages/audiobookdl/sources/nextory.py", line 135, in download_want_to_read_list
    want_to_read_id = self.download_want_to_read_id()
  File "/home/nicklas/audiobook-dl/venv/lib/python3.10/site-packages/audiobookdl/sources/nextory.py", line 121, in download_want_to_read_id
    products_lists = self._session.get(
KeyError: 'product_lists'
`

**Comment by frankhommers** [comment]
I have the same problem.

**Comment by hcbille** [comment]
This is still happening. 
I have an account that can be used if an account is needed for troubleshooting.
