### ISSUE TITLE
Cannot Get Working

### ISSUE THREAD

**Issue by Graywaren** [jo1gi/audiobook-dl#94]
**Installation method:**
Pip

**Version:**
*Py 312, 0.7.3*

**Describe the bug**
I'm really rather frustrated as there is no guide or documentation on how to go from "I want to download my audiobooks and have never used a cli tool before" to "audiobook-dl is installed and working".  So I'm probably doing something wrong, but as I've only gotten this far through hours of internet searching on how to do anything. I installed python, finally figured out I needed to have -m before the pip install command, got audiobook-dl installed as far as I can tell... had it not work, finally found a closed issue stating it needed to be added to the path, trial and error and finally finding some random internet person mentioning to restart cmd after adding it later >.> and I finally got that working.. so now audiobook-dl is installed and should in theory work. 

I tried to change the output path so I could find where anything would go, but that's not working, so I gave up and just wanted to try downloading one audiobook. I tried having a config file and that didn't work either, so I just put the cookie path in manually. From other issues I browsed, I know I need the listen URL for everand. I exported the cookies from Firefox with the extension recommended. I tried both the www.everand.com ones and the everand.com ones neither worked. Pls help as I need to cancel my account asap before I get billed again.

**Command output**

C:\Users\Ronan>audiobook-dl -cD:\Ronan\Books\X0 Audiobooks\audiobook-dl files\cookies\everand-cookies.txt https://www.everand.com/listen/638079282 --debug
DEBUG audiobook-dl 0.7.3
DEBUG python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
 INFO Finding compatible source
ERROR: The url you provided is not supported by audiobook-dl

Supported services are:
 • audiobooks.com
 • Blinkist
 • BookBeat
 • Chirp
 • eReolen
 • Everand
 • Libby
 • Librivox
 • Mofibo
 • Nextory
 • Overdrive
 • Podimo
 • Saxo
 • Scribd
 • Storytel
 • YourCloudLibrary

Traceback
Traceback (most recent call last):
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 31, in main
    process_url(url, options, config)
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\__main__.py", line 49, in process_url
    source = find_compatible_source(url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ronan\AppData\Local\Programs\Python\Python312\Lib\site-packages\audiobookdl\sources\__init__.py", line 28, in find_compatible_source
    raise NoSourceFound
audiobookdl.exceptions.NoSourceFound

**Comment by Graywaren** [comment]
Okay, more experimenting and I figured out this issue. For anyone else who stumbles upon this: you cannot have ANY SPACES in your cookie file or output etc. paths. So my "xo audiobooks" and "audiobook-dl files" folder names were breaking it. Once given a path with no spaces it was able to download the books correctly.
